const images = {
  dish1: require('../static/images/dish/5.jpg'),
  dish2: require('../static/images/dish/7.jpg'),
  dish3: require('../static/images/dish/8.jpg'),
  dish4: require('../static/images/dish/9.jpg'),
  dish5: require('../static/images/dish/11.jpg'),
  dish6: require('../static/images/dish/12.jpg'),
  dish7: require('../static/images/dish/13.jpg'),
  dish8: require('../static/images/dish/15.jpg'),
  dish9: require('../static/images/dish/16.jpg'),
  dish10: require('../static/images/dish/17.jpg'),
  dish11: require('../static/images/dish/20.jpg'),
  dish12: require('../static/images/dish/22.jpg'),
  dish13: require('../static/images/dish/23.jpg'),
  dish14: require('../static/images/dish/24.jpg'),
  dish15: require('../static/images/dish/25.jpg'),
  dish16: require('../static/images/dish/26.jpg'),
  dish17: require('../static/images/dish/27.jpg'),
  dish18: require('../static/images/dish/28.jpg'),
  dish19: require('../static/images/dish/29.jpg'),
  dish20: require('../static/images/dish/30.jpg'),
  dish21: require('../static/images/dish/31.jpg'),
  dish22: require('../static/images/dish/32.jpg'),
  dish23: require('../static/images/dish/33.jpg'),
  dish24: require('../static/images/dish/39.jpg'),
  dish25: require('../static/images/dish/40.jpg'),
  dish26: require('../static/images/dish/42.jpg'),
  dish27: require('../static/images/dish/43.jpg')
}

export default images;
